# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rlearn.distributed.experience import buffer_pb2 as rlearn_dot_distributed_dot_experience_dot_buffer__pb2


class ReplayBufferStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ServiceReady = channel.unary_unary(
            '/replayBuffer.ReplayBuffer/ServiceReady',
            request_serializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.ServiceReadyReq.SerializeToString,
            response_deserializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.ServiceReadyResp.FromString,
        )
        self.InitBuf = channel.unary_unary(
            '/replayBuffer.ReplayBuffer/InitBuf',
            request_serializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.InitBufReq.SerializeToString,
            response_deserializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.InitBufResp.FromString,
        )
        self.LearnerSetVersion = channel.unary_unary(
            '/replayBuffer.ReplayBuffer/LearnerSetVersion',
            request_serializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.LearnerSetVersionReq.SerializeToString,
            response_deserializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.LearnerSetVersionResp.FromString,
        )
        self.UploadData = channel.stream_unary(
            '/replayBuffer.ReplayBuffer/UploadData',
            request_serializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.UploadDataReq.SerializeToString,
            response_deserializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.UploadDataResp.FromString,
        )
        self.DownloadData = channel.unary_stream(
            '/replayBuffer.ReplayBuffer/DownloadData',
            request_serializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.DownloadDataReq.SerializeToString,
            response_deserializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.DownloadDataResp.FromString,
        )
        self.Stop = channel.unary_unary(
            '/replayBuffer.ReplayBuffer/Stop',
            request_serializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.StopReq.SerializeToString,
            response_deserializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.StopResp.FromString,
        )


class ReplayBufferServicer(object):
    """The greeting service definition.
    """

    def ServiceReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitBuf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LearnerSetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplayBufferServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ServiceReady': grpc.unary_unary_rpc_method_handler(
            servicer.ServiceReady,
            request_deserializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.ServiceReadyReq.FromString,
            response_serializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.ServiceReadyResp.SerializeToString,
        ),
        'InitBuf': grpc.unary_unary_rpc_method_handler(
            servicer.InitBuf,
            request_deserializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.InitBufReq.FromString,
            response_serializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.InitBufResp.SerializeToString,
        ),
        'LearnerSetVersion': grpc.unary_unary_rpc_method_handler(
            servicer.LearnerSetVersion,
            request_deserializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.LearnerSetVersionReq.FromString,
            response_serializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.LearnerSetVersionResp.SerializeToString,
        ),
        'UploadData': grpc.stream_unary_rpc_method_handler(
            servicer.UploadData,
            request_deserializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.UploadDataReq.FromString,
            response_serializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.UploadDataResp.SerializeToString,
        ),
        'DownloadData': grpc.unary_stream_rpc_method_handler(
            servicer.DownloadData,
            request_deserializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.DownloadDataReq.FromString,
            response_serializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.DownloadDataResp.SerializeToString,
        ),
        'Stop': grpc.unary_unary_rpc_method_handler(
            servicer.Stop,
            request_deserializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.StopReq.FromString,
            response_serializer=rlearn_dot_distributed_dot_experience_dot_buffer__pb2.StopResp.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'replayBuffer.ReplayBuffer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ReplayBuffer(object):
    """The greeting service definition.
    """

    @staticmethod
    def ServiceReady(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(request, target, '/replayBuffer.ReplayBuffer/ServiceReady',
                                             rlearn_dot_distributed_dot_experience_dot_buffer__pb2.ServiceReadyReq.SerializeToString,
                                             rlearn_dot_distributed_dot_experience_dot_buffer__pb2.ServiceReadyResp.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitBuf(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(request, target, '/replayBuffer.ReplayBuffer/InitBuf',
                                             rlearn_dot_distributed_dot_experience_dot_buffer__pb2.InitBufReq.SerializeToString,
                                             rlearn_dot_distributed_dot_experience_dot_buffer__pb2.InitBufResp.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LearnerSetVersion(request,
                          target,
                          options=(),
                          channel_credentials=None,
                          call_credentials=None,
                          insecure=False,
                          compression=None,
                          wait_for_ready=None,
                          timeout=None,
                          metadata=None):
        return grpc.experimental.unary_unary(request, target, '/replayBuffer.ReplayBuffer/LearnerSetVersion',
                                             rlearn_dot_distributed_dot_experience_dot_buffer__pb2.LearnerSetVersionReq.SerializeToString,
                                             rlearn_dot_distributed_dot_experience_dot_buffer__pb2.LearnerSetVersionResp.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadData(request_iterator,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/replayBuffer.ReplayBuffer/UploadData',
                                              rlearn_dot_distributed_dot_experience_dot_buffer__pb2.UploadDataReq.SerializeToString,
                                              rlearn_dot_distributed_dot_experience_dot_buffer__pb2.UploadDataResp.FromString,
                                              options, channel_credentials,
                                              insecure, call_credentials, compression, wait_for_ready, timeout,
                                              metadata)

    @staticmethod
    def DownloadData(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_stream(request, target, '/replayBuffer.ReplayBuffer/DownloadData',
                                              rlearn_dot_distributed_dot_experience_dot_buffer__pb2.DownloadDataReq.SerializeToString,
                                              rlearn_dot_distributed_dot_experience_dot_buffer__pb2.DownloadDataResp.FromString,
                                              options, channel_credentials,
                                              insecure, call_credentials, compression, wait_for_ready, timeout,
                                              metadata)

    @staticmethod
    def Stop(request,
             target,
             options=(),
             channel_credentials=None,
             call_credentials=None,
             insecure=False,
             compression=None,
             wait_for_ready=None,
             timeout=None,
             metadata=None):
        return grpc.experimental.unary_unary(request, target, '/replayBuffer.ReplayBuffer/Stop',
                                             rlearn_dot_distributed_dot_experience_dot_buffer__pb2.StopReq.SerializeToString,
                                             rlearn_dot_distributed_dot_experience_dot_buffer__pb2.StopResp.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
