# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rllearn.distributed import buffer_pb2 as tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2


class ReplayBufferStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ServiceReady = channel.unary_unary(
            '/replayBuffer.ReplayBuffer/ServiceReady',
            request_serializer=tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.ServiceReadyReq.SerializeToString,
            response_deserializer=tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.ServiceReadyResp.FromString,
        )
        self.UploadData = channel.unary_unary(
            '/replayBuffer.ReplayBuffer/UploadData',
            request_serializer=tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.UploadDataReq.SerializeToString,
            response_deserializer=tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.UploadDataResp.FromString,
        )
        self.DownloadData = channel.unary_unary(
            '/replayBuffer.ReplayBuffer/DownloadData',
            request_serializer=tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.DownloadDataReq.SerializeToString,
            response_deserializer=tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.DownloadDataResp.FromString,
        )


class ReplayBufferServicer(object):
    """The greeting service definition.
    """

    def ServiceReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplayBufferServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ServiceReady': grpc.unary_unary_rpc_method_handler(
            servicer.ServiceReady,
            request_deserializer=tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.ServiceReadyReq.FromString,
            response_serializer=tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.ServiceReadyResp.SerializeToString,
        ),
        'UploadData': grpc.unary_unary_rpc_method_handler(
            servicer.UploadData,
            request_deserializer=tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.UploadDataReq.FromString,
            response_serializer=tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.UploadDataResp.SerializeToString,
        ),
        'DownloadData': grpc.unary_unary_rpc_method_handler(
            servicer.DownloadData,
            request_deserializer=tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.DownloadDataReq.FromString,
            response_serializer=tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.DownloadDataResp.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'replayBuffer.ReplayBuffer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ReplayBuffer(object):
    """The greeting service definition.
    """

    @staticmethod
    def ServiceReady(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(request, target, '/replayBuffer.ReplayBuffer/ServiceReady',
                                             tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.ServiceReadyReq.SerializeToString,
                                             tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.ServiceReadyResp.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadData(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/replayBuffer.ReplayBuffer/UploadData',
                                             tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.UploadDataReq.SerializeToString,
                                             tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.UploadDataResp.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadData(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(request, target, '/replayBuffer.ReplayBuffer/DownloadData',
                                             tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.DownloadDataReq.SerializeToString,
                                             tipealgs_dot_ml_dot_rl_dot_distributed_dot_buffer__pb2.DownloadDataResp.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
