# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rlearn/distributed/gradient/param.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\'rlearn/distributed/gradient/param.proto\x12\x06params\"$\n\x0fServiceReadyReq\x12\x11\n\trequestId\x18\x01 \x01(\t\"4\n\x10ServiceReadyResp\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x11\n\trequestId\x18\x02 \x01(\t\"\xc0\x01\n\tStartMeta\x12\x10\n\x08syncStep\x18\x01 \x01(\r\x12\x13\n\x0btrainerType\x18\x02 \x01(\t\x12\x12\n\nbufferType\x18\x03 \x01(\t\x12\x12\n\nbufferSize\x18\x04 \x01(\x04\x12\x16\n\x0emaxEpisodeStep\x18\x05 \x01(\x03\x12\x17\n\x0f\x61\x63tionTransform\x18\x06 \x01(\t\x12\x11\n\trequestId\x18\x07 \x01(\t\x12\x11\n\tbatchSize\x18\x08 \x01(\r\x12\r\n\x05gamma\x18\t \x01(\x02\"\x1d\n\x08StartReq\x12\x11\n\trequestId\x18\x01 \x01(\t\"N\n\tStartResp\x12!\n\x04meta\x18\x01 \x01(\x0b\x32\x11.params.StartMetaH\x00\x12\x13\n\tchunkData\x18\x02 \x01(\x0cH\x00\x42\t\n\x07request\">\n\x07SyncReq\x12\x13\n\trequestId\x18\x01 \x01(\tH\x00\x12\x13\n\tchunkData\x18\x02 \x01(\x0cH\x00\x42\t\n\x07request\".\n\x0bWeightsMeta\x12\x11\n\trequestId\x18\x01 \x01(\t\x12\x0c\n\x04stop\x18\x02 \x01(\x08\"O\n\x08SyncResp\x12#\n\x04meta\x18\x01 \x01(\x0b\x32\x13.params.WeightsMetaH\x00\x12\x13\n\tchunkData\x18\x02 \x01(\x0cH\x00\x42\t\n\x07request\"!\n\x0cTerminateReq\x12\x11\n\trequestId\x18\x01 \x01(\t\"=\n\rTerminateResp\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\x12\x0b\n\x03\x65rr\x18\x02 \x01(\t\x12\x11\n\trequestId\x18\x03 \x01(\t2\xec\x01\n\x06Params\x12\x43\n\x0cServiceReady\x12\x17.params.ServiceReadyReq\x1a\x18.params.ServiceReadyResp\"\x00\x12\x30\n\x05Start\x12\x10.params.StartReq\x1a\x11.params.StartResp\"\x00\x30\x01\x12/\n\x04Sync\x12\x0f.params.SyncReq\x1a\x10.params.SyncResp\"\x00(\x01\x30\x01\x12:\n\tTerminate\x12\x14.params.TerminateReq\x1a\x15.params.TerminateResp\"\x00\x42*\n\x14io.grpc.examples.envB\nParamProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_SERVICEREADYREQ = DESCRIPTOR.message_types_by_name['ServiceReadyReq']
_SERVICEREADYRESP = DESCRIPTOR.message_types_by_name['ServiceReadyResp']
_STARTMETA = DESCRIPTOR.message_types_by_name['StartMeta']
_STARTREQ = DESCRIPTOR.message_types_by_name['StartReq']
_STARTRESP = DESCRIPTOR.message_types_by_name['StartResp']
_SYNCREQ = DESCRIPTOR.message_types_by_name['SyncReq']
_WEIGHTSMETA = DESCRIPTOR.message_types_by_name['WeightsMeta']
_SYNCRESP = DESCRIPTOR.message_types_by_name['SyncResp']
_TERMINATEREQ = DESCRIPTOR.message_types_by_name['TerminateReq']
_TERMINATERESP = DESCRIPTOR.message_types_by_name['TerminateResp']
ServiceReadyReq = _reflection.GeneratedProtocolMessageType('ServiceReadyReq', (_message.Message,), {
    'DESCRIPTOR': _SERVICEREADYREQ,
    '__module__': 'rlearn.distributed.gradient.param_pb2'
    # @@protoc_insertion_point(class_scope:params.ServiceReadyReq)
})
_sym_db.RegisterMessage(ServiceReadyReq)

ServiceReadyResp = _reflection.GeneratedProtocolMessageType('ServiceReadyResp', (_message.Message,), {
    'DESCRIPTOR': _SERVICEREADYRESP,
    '__module__': 'rlearn.distributed.gradient.param_pb2'
    # @@protoc_insertion_point(class_scope:params.ServiceReadyResp)
})
_sym_db.RegisterMessage(ServiceReadyResp)

StartMeta = _reflection.GeneratedProtocolMessageType('StartMeta', (_message.Message,), {
    'DESCRIPTOR': _STARTMETA,
    '__module__': 'rlearn.distributed.gradient.param_pb2'
    # @@protoc_insertion_point(class_scope:params.StartMeta)
})
_sym_db.RegisterMessage(StartMeta)

StartReq = _reflection.GeneratedProtocolMessageType('StartReq', (_message.Message,), {
    'DESCRIPTOR': _STARTREQ,
    '__module__': 'rlearn.distributed.gradient.param_pb2'
    # @@protoc_insertion_point(class_scope:params.StartReq)
})
_sym_db.RegisterMessage(StartReq)

StartResp = _reflection.GeneratedProtocolMessageType('StartResp', (_message.Message,), {
    'DESCRIPTOR': _STARTRESP,
    '__module__': 'rlearn.distributed.gradient.param_pb2'
    # @@protoc_insertion_point(class_scope:params.StartResp)
})
_sym_db.RegisterMessage(StartResp)

SyncReq = _reflection.GeneratedProtocolMessageType('SyncReq', (_message.Message,), {
    'DESCRIPTOR': _SYNCREQ,
    '__module__': 'rlearn.distributed.gradient.param_pb2'
    # @@protoc_insertion_point(class_scope:params.SyncReq)
})
_sym_db.RegisterMessage(SyncReq)

WeightsMeta = _reflection.GeneratedProtocolMessageType('WeightsMeta', (_message.Message,), {
    'DESCRIPTOR': _WEIGHTSMETA,
    '__module__': 'rlearn.distributed.gradient.param_pb2'
    # @@protoc_insertion_point(class_scope:params.WeightsMeta)
})
_sym_db.RegisterMessage(WeightsMeta)

SyncResp = _reflection.GeneratedProtocolMessageType('SyncResp', (_message.Message,), {
    'DESCRIPTOR': _SYNCRESP,
    '__module__': 'rlearn.distributed.gradient.param_pb2'
    # @@protoc_insertion_point(class_scope:params.SyncResp)
})
_sym_db.RegisterMessage(SyncResp)

TerminateReq = _reflection.GeneratedProtocolMessageType('TerminateReq', (_message.Message,), {
    'DESCRIPTOR': _TERMINATEREQ,
    '__module__': 'rlearn.distributed.gradient.param_pb2'
    # @@protoc_insertion_point(class_scope:params.TerminateReq)
})
_sym_db.RegisterMessage(TerminateReq)

TerminateResp = _reflection.GeneratedProtocolMessageType('TerminateResp', (_message.Message,), {
    'DESCRIPTOR': _TERMINATERESP,
    '__module__': 'rlearn.distributed.gradient.param_pb2'
    # @@protoc_insertion_point(class_scope:params.TerminateResp)
})
_sym_db.RegisterMessage(TerminateResp)

_PARAMS = DESCRIPTOR.services_by_name['Params']
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'\n\024io.grpc.examples.envB\nParamProtoP\001\242\002\003HLW'
    _SERVICEREADYREQ._serialized_start = 51
    _SERVICEREADYREQ._serialized_end = 87
    _SERVICEREADYRESP._serialized_start = 89
    _SERVICEREADYRESP._serialized_end = 141
    _STARTMETA._serialized_start = 144
    _STARTMETA._serialized_end = 336
    _STARTREQ._serialized_start = 338
    _STARTREQ._serialized_end = 367
    _STARTRESP._serialized_start = 369
    _STARTRESP._serialized_end = 447
    _SYNCREQ._serialized_start = 449
    _SYNCREQ._serialized_end = 511
    _WEIGHTSMETA._serialized_start = 513
    _WEIGHTSMETA._serialized_end = 559
    _SYNCRESP._serialized_start = 561
    _SYNCRESP._serialized_end = 640
    _TERMINATEREQ._serialized_start = 642
    _TERMINATEREQ._serialized_end = 675
    _TERMINATERESP._serialized_start = 677
    _TERMINATERESP._serialized_end = 738
    _PARAMS._serialized_start = 741
    _PARAMS._serialized_end = 977
# @@protoc_insertion_point(module_scope)
